<!DOCTYPE html>
<html lang="en">

<?php

include("passwords.php");

// Connect to the database
$dbconnect = mysqli_connect(DB_HOST, DB_USERNAME, DB_PASSWORD, DB_NAME);

if (mysqli_connect_errno())
{
    echo "Connection failed:".mysqli_connect_error();
    exit;
}

?>

<!-- The code below was generated by ChatGPT then edited by Alexander Motufoua -->
<head>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="music website for music stuff">
    <meta name="keywords" content="music, Alexander Motufoua">
    
    <meta name="author" content="Alexander Motufoua">
   
    <title>Musical Magic</title>
    
    <!-- stylesheet area -->
    <link rel="stylesheet" href="music_stylesheet.css">

    <!-- icon for tabs & bookmarks -->
    <link rel="icon" type="logos/" href="musicnotes.ico">

</head>